export const IS_OPENED = 'IS_OPENED'


export const FETCHED_QUIZES_START = 'FETCHED_QUIZES_START'
export const FETCHED_QUIZES_SUCCESS = 'FETCHED_QUIZES_SUCCESS'
export const FETCHED_QUIZES_ERROR = 'FETCHED_QUIZES_ERROR'

export const FETCHED_QUIZ_SUCCESS = 'FETCHED_QUIZ_SUCCESS'
export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'

export const FINISHED_QUIZ = 'FINISHED_QUIZ'
export const SWITCH_NEXT_TO_QUIZ = 'SWITCH_NEXT_TO_QUIZ'
export const  RETRY_QUIZ_HANDLER = 'RETRY_QUIZ_HANDLER'


